- .bowerrc
- .gitignore
- bower.json
- gruntfile.js
This strips out references to bower, and any linting/beautifying done on js. I don't see anything else to be removed, let me know if you do though.
> Remove cruft

- public/d3fc-showcase.html
- public/index.html
You can merge it so that you can start working on your stuff.
> Structure for further work

- public/home-controller.js
- public/index.html
> Use angular to open new openfin window (closes #4)

- gruntfile.js
- package.json
- public/assets/css/style.css
- public/assets/js/app.min.js
- public/d3fc-showcase.html
> Load showcase through npm and build into openfin project

- .gitignore
After building the new less there's a leftover map file
> Ignore map file too

- .gitignore
- gruntfile.js
- package.json
No need to say anything. Proof is in the pudding.
> Added download of zip file to the build process. Closes #15

- public/app.js
- public/index.html
- public/search-controller.js
- public/search.html
- public/stock-controller.js
- public/stockData.html
- public/thumbnails-controller.js
- public/thumbnails.html
This first commit enables searching with the search bar. This can be achieved by pressing enter while the input field has focus, or by clicking the search button. The user will be taken to a 'searching' page while the application searches for the requested data. When the data is found they will be redirected to the page showing the data.
The input is not sanitised at all.
Currently we are not connecting to anything, but instead I've included a dummy 1s delay, then showing them the input search as a bullet point.
Internally this introduces ngRoute, and the scaffolding of other controllers and html pages.
One thing to note is that I've not organised the file structure at all: I don't want to commit us to a structure this early while the project is still growing.
N.B. Please don't close this …
> Implement search (part 1)

- public/app.js
- public/index.html
- public/quandl-service.js
- public/search-controller.js
- public/stock-controller.js
- public/stockData.html
Now the app will connect to quandl, using the input string as a search and return a bullet pointed list of results.
> Implement search (part 2: quandl service)

- .travis.yml
> Tidy travis file

- README.md
Do you think this is enough/sufficient?
> Add documentation for the exe (closes #36)

- public/thumbnails-controller.js
- public/thumbnails.html
The issue was the windows need to be uniquely named or OpenFin throws an error. However this name is not being used as the window name. I've not made an attempt to rectify this as we're not yet at the stage of editing any of the d3fc-showcase.
> Window does not open when one is already opened (closes #39)

- public/index.html
- public/search-controller.js
- public/search.html
- public/stock-controller.js
- src/assets/styles/style.less
Is there a better way to center the logo rather than surrounding the col with empty col-sm-4?
> Make scottlogic logo a link back to the homepage (closes #29)

- public/index.html
- src/assets/styles/style.less
This centers logo and re-formats html to what webstorm sees as a standard spacing (avoids indentation for some tags to improve readability).
> Center logo, closes #72

- public/index.html
- public/search-controller.js
Added a small UI improvement too.
> Disabled searching for empty search query (closes #71)

- public/index.html
- public/logo.svg
This is fix for 75, still working on 62, don't close the branch.
> SVG changed, window working. Fixes #75

- package.json
> Install dev dependencies for d3fc-showcase on npm install

- .travis.yml
> Travis no longer need to npm install d3fc-showcase

- package.json
- src/services/openfin-service.js
This closes #107 integrating with quandl
> Adding the get parameter with the ticker (quanld integration)

- package.json
- src/assets/styles/style.less
- src/index.html
- src/sidebars/favourites/favourite-preview.html
- src/sidebars/favourites/favourites.js
> Display stock

- src/services/quandl-service.js
- src/sidebars/search/search.js
No longer using the search api on quandl to find a favourite, but getting the specific data.
> Duplicate favourites

- src/app.js
- src/index.html
- src/sidebars/favourites/favourite-preview.html
- src/sidebars/favourites/favourites.js
- src/sidebars/search/search-preview.html
- src/sidebars/search/search.js
- src/sidebars/star.html
- src/sidebars/star.js
Adds the favourite icon to the favourite tiles.
> Favourite icon

- src/assets/styles/style.less
- src/sidebars/favourites/favourites.js
Also adds the discontinuity provider.
> Shading on spark charts

- src/assets/styles/favourites.less
- src/assets/styles/logo.less
- src/assets/styles/search.less
- src/assets/styles/sidebar.less
- src/assets/styles/style.less
- src/assets/styles/variables.less
- src/index.html
> Split less file

- src/assets/styles/favourites.less
- src/assets/styles/search.less
- src/assets/styles/sidebar.less
- src/assets/styles/style.less
- src/assets/styles/variables.less
- src/index.html
- src/sidebars/favourites/favourite-preview.html
- src/sidebars/search/search-preview.html
- src/sidebars/sidebar-controller.js
- src/sidebars/star.html
Doesn't use the correct fonts yet.
> Style sidebars

- src/app.js
- src/index.html
- src/main-controller.js
- src/sidebars/favourites/favourite-preview.html
- src/sidebars/favourites/favourites.js
- src/sidebars/search/search.js
First step of #154 . The controllers in the index file were all over the place, so I've moved them around so they're covering the correct (and obvious) scopes. 
It didn't make sense to have the sidebar controller knowing the selected stock as the showcase needs to know that, and it has nothing to do with the sidebar. Hence the introduction of a new, main, controller.
> Make search results clickable (move selection into main-controller)

- src/index.html
- src/sidebars/search/search-preview.html
- src/sidebars/search/search.js
And it's out of the park ... !
> Make search results clickable

- src/assets/styles/style.less
Closes #162 - don't worry about it
> Fix rendering when adding indicators. Closes #162.

- src/assets/styles/star.less
- src/assets/styles/style.less
- src/sidebars/favourites/favourite-preview.html
- src/sidebars/search/search-preview.html
- src/sidebars/star.html
- src/sidebars/star.js
Corrects colours, removes duplicated colour logic into the css, fixes the star colour on search result selection.
> Fix star styling (refactor logic into classes and css)

- src/index.html
- src/sidebars/favourites/favourite-preview.html
- src/sidebars/search/search-preview.html
I don't think the splitters belong in the search and favourite files, so I've split (haha) them out. Also reinstated the ones at the bottom of the lists.
> Move splitters out of tilesand add to the end

- src/index.html
- src/sidebars/search/search.js
> Fix search tab transition when clicking search button

- src/assets/styles/style.less
- src/assets/styles/toolbar.less
- src/assets/styles/variables.less
- src/sidebars/sidebar.less
> toolbar fix

- src/services/store-service.js
Classic js falsey. Favourites will need a bit of robustness testing after this has been merged.
> Fix removing 0-index favourite

- src/sidebars/favourites/favourite.html
> The software always starts selected.

- src/index.html
- src/services/quandl-service.js
- src/sidebars/search/search-controller.js
- src/sidebars/search/search.less
This provides a basic placeholder until we have a design.
> Friendly message

- src/sidebars/favourites/favourite.html
Yeah... it actually makes a difference.
> Fix for bug with auto opening.

- src/assets/styles/variables.less
- src/sidebars/favourites/favourite.html
- src/sidebars/favourites/favourites.less
- src/sidebars/favourites/minichart/minichart.less
- src/sidebars/search/search.less
- src/sidebars/sidebar-controller.js
This is so the new rendered styles can be pushed to gh-pages for Rui to play with.
> Update sidebar styling

- src/sidebars/favourites/minichart/minichart-controller.js
- src/sidebars/favourites/minichart/minichart.less
Only displays half the point at the moment.
> Add point at the end of the minichart

- src/assets/svg/favourite_HOVER.svg
- src/assets/svg/favourite_OFF.svg
- src/assets/svg/favourite_ON.svg
- src/index.html
- src/sidebars/favourites/favourite.html
- src/sidebars/search/search.html
- src/sidebars/search/search.less
- src/sidebars/star/star-controller.js
- src/sidebars/star/star-directive.js
- src/sidebars/star/star.html
- src/sidebars/star/star.less
Depends on the changes for the selection service.
> Replace favourite icons

- src/assets/styles/style.less
- src/assets/svg/favourite_TOP.svg
- src/index.html
- src/sidebars/sidebar.less
This replaces the top star icon with the new svg. The padding etc. will affect the search icon, but given that is to be replaced I haven't bothered making it perfect.
> Top star icon

- gruntfile.js
- package.json
- src/index.html
> Remove bootstrap

- src/assets/styles/custom-scroll.less
- src/showcase/showcase-changes.less
- src/sidebars/favourites/favourites.less
- src/sidebars/search/search.less
Tidy for the less files.
Keep this branch open, I'll use it for the missing separator on the search tab #239
> Tidy LESS files

- src/assets/styles/style.less
- src/index.html
- src/sidebars/search/search.less
> Remove blue shading (closes #250)

- src/app.js
- src/index.html
- src/services/store-service.js
- src/sidebars/favourites/favourite-controller.js
- src/sidebars/favourites/favourite.html
- src/sidebars/favourites/favourites.less
- src/sidebars/favourites/geometry-service.js
- src/sidebars/favourites/hover-service.js
- src/sidebars/favourites/tearout.html
- src/sidebars/favourites/tearout.js
- src/sidebars/search/search-controller.js
- src/sidebars/sidebar-controller.js
- src/sidebars/star/star-controller.js
- src/sidebars/star/star.html
Re-ordering the favourite cards using the OpenFin API and tearout functionality. Note: This is purely re-ordering -- no torn out window will persist.
I'm not entirely sure how robust this is -- I think it'll need some exercise.
Also there is a fair amount of new code here -- I don't know into how much detail you'll want to go.
> Reorder cards

- src/assets/styles/style.less
- src/assets/styles/variables.less
- src/showcase/showcase-changes.less
- src/showcase/showcase.html
- src/toolbar/toolbar.less
A load of tweaks to style the showcase.
> Style showcase

- src/showcase/showcase-changes.less
- src/sidebars/favourites/minichart/minichart.less
- src/sidebars/search/search.less
- src/sidebars/sidebar.less
Does most of the styling as specified. Doesn't merge the dropdown window with the icon above -- will have to investigate to see how much work that is.
> Dropdown style

- src/index.html
- src/sidebars/search/search-controller.js
> Select search results with up/down arrow keys

- src/index.html
- src/sidebars/sidebar-directive.js
- src/sidebars/sidebar.html
- src/toolbar/toolbar-directive.js
- src/toolbar/toolbar.html
> Directive split

- src/toolbar/toolbar.html
- src/toolbar/toolbar.less
Temporarily removing this feature to merge into master.
> Toggle off compact view

- src/app.json
This is hotfix for gh-pages problem
> Adding missing parameters in app.json

- src/sidebars/favourites/favourite-directive.js
- src/sidebars/favourites/favourites.less
- src/sidebars/sidebar.html
Changes the colour of the empty space left behind by a tearout card.
> Hover colour

- src/sidebars/favourites/minichart/minichart-controller.js
- src/sidebars/favourites/minichart/minichart.html
- src/sidebars/favourites/minichart/minichart.less
Transparency now comes through without extra styling
> Simplify minichart

- README.md
- gruntfile.js
- package.json
- src/.eslintrc
- src/assets/styles/style.less
- src/index.html
- src/main/main.html
- src/showcase/showcase-changes.less
- src/showcase/showcase-directive.js
As an added bonus, if the window is in compact mode, Bitflux isn't initialised.
**NOTE:** `npm install` will be needed after merging.
> Update to Bitflux 1.0.1

- gruntfile.js
- src/app.js
- src/config-service.js
- src/parentApp.js
- src/window-service.js
> Add config service

- gruntfile.js
Adds `window-service` to the gruntfile exclusions
> Fix angular error

- src/sidebars/favourites/favourite-controller.js
- src/sidebars/favourites/favourite-directive.js
- src/sidebars/favourites/favourite.html
- src/sidebars/favourites/favourites.less
- src/sidebars/favourites/tearout.js
- src/sidebars/sidebar.html
- src/sidebars/star/star.html
- src/store-service.js
- src/toolbar/toolbar-controller.js
Also included is a commit to prevent the icons being dragged out of the main window.
> Double click on compact favourite restores window

- src/sidebars/favourites/tearout.js
- src/toolbar/toolbar-controller.js
- src/window-service.js
> Dispose of old event listeners correctly

- src/closedWindows/closedCard-controller.js
- src/sidebars/sidebar.html
- src/store-service.js
- src/window-service.js
This removes the entry from the recently closed windows when the window is restored.
> Set window to open when recovered

- src/parent-controller.js
- src/store-service.js
- src/window-service.js
> Only dispatch event to relevant window

- src/window-service.js
> Keep window on screen on window start up

- src/sidebars/favourites/tearout.js
Remove the internal fluent API.
> Refactor tearout

- gruntfile.js
- package.json
- src/app.js
- src/sidebars/sidebar.html
- src/sidebars/sidebar.less
- src/sidebars/version-directive.js
Adds a version number in the lower left corner for #424
> Add version info

- src/window-service.js
This reverts commit d178fc62a06454bf6490c5e0bed66c5306300c6a.
For issue #447
> Revert "Taskbar consideration"

- src/app.js
- src/services/currentWindow-service.js
- src/sidebars/sidebar-controller.js
- src/sidebars/sidebar.html
- src/sidebars/sidebar.less
An attempt to resolve #412 without having to add an icon, and it shouldn't be too hard to add an icon in any case.
> Open repo when clicking on version number

- src/window-service.js
> Re-attempt for taskbar compensation

- src/sidebars/favourites/tearout-directive.js
- src/sidebars/search/search-controller.js
> Tear in/out search consistency

- gruntfile.js
- src/app.json
- src/main/version/version-controller.js
Once this is approved I'll rename the repo too.
> Rename app to StockFlux

- README.md
- gruntfile.js
Also change the target zip file in the Gruntfile
> Rename to Stockflux in Readme

- src/assets/styles/custom-scroll.less
- src/closedWindows/closedCard.less
- src/sidebars/sidebar.html
- src/sidebars/sidebar.less
> Style Changes

- src/sidebars/favourites/favourite.html
- src/sidebars/search/search.html
- src/sidebars/sidebar.less
Another good PR. Changes the reused ID to a class. #457
> Fix stock name word wrap issue

- src/assets/styles/custom-scroll.less
- src/sidebars/sidebar.less
> Remove empty space at bottom of search

- src/sidebars/sidebar.less
> Hide closed window; fix search result positioning #475

- gruntfile.js
- package.json
- src/config-service.js
> Context menu

- src/icon/icon.html
- src/sidebars/search/search.html
- src/sidebars/search/search.less
adds close icon to search in compact view to make a more obvious way for users to exit the compact search view.
> Compact search exit

- package.json
- src/showcase/showcase-directive.js
- src/showcase/showcase.html
- src/store-service.js
> Initial Indicator + Indicator Persist. 

- src/sidebars/sidebar.less
The shadow is thrown to top left, rather than bottom right. Given that left is dark, this actually looks very nice to me.
Also closes #485
> Shadow is back on closed window.

- src/main/main.html
> Don't show version in compact view

- src/assets/styles/mixins.less
- src/assets/styles/style.less
- src/closedWindows/closedCard/closedCard.html
- src/closedWindows/closedCard/closedCard.less
- src/config-service.js
- src/showcase/showcase-changes.less
- src/sidebars/favourites/minichart/minichart.less
- src/sidebars/sidebar.less
Fixes 7/8 in #494. Indicator close buttons need a new SVG/png to implement, so I'm waiting on that.
Also fixes an issue in #497
> Chart style updates

- src/config-service.js
> Show more data on chart initially

- src/sidebars/sidebar.less
- src/window-service.js
> Window shunting

- src/config-service.js
- src/sidebars/favourites/tearout-directive.js
> Have different window offsets depending on compactness

- src/sidebars/favourites/tearout-directive.js
closes #526 
I missed one in #459 
(This also seems to resolve a lot of the cache inconsistencies we were having)
> Remove favourite on tearout

- src/config-service.js
> Add resize region

- src/sidebars/search/search-controller.js
- src/sidebars/search/search.html
> Fix disappearing star on dragover

- README.md
- package.json
- src/main/version/version-controller.js
Adds additional info about the release into the readme.
> Release v9.2.0

- src/window-service.js
> Fix window tracker not disposing windows properly

- src/closedWindows/closedWindowList/closedWindowList-controller.js
- src/closedWindows/closedWindowList/closedWindowList.html
- src/store-service.js
Feedback appreciated, I'm not 100% on this approach
> Autohide the closed windows display

- src/sidebars/search/search-controller.js
- src/sidebars/search/search.html
- src/sidebars/search/search.less
> Add search loading message

- src/assets/styles/custom-scroll.less
- src/sidebars/search/search.less
- src/sidebars/star/star-controller.js
- src/sidebars/star/star.html
- src/sidebars/star/star.less
> Confirmation window

- src/sidebars/search/search-controller.js
> Fix search results not updating favourites on tearout

- src/closedWindows/closedWindowList/closedWindowList.html
> Hide all closed window list if the icon shouldn't be shown

- src/assets/styles/custom-scroll.less
- src/sidebars/search/search.less
- src/sidebars/sidebar.less
> Scrollbar height fix. Closes #564

- src/sidebars/favourites/favourite-controller.js
- src/sidebars/sidebar.html
The solution I have in mind for #326 to give a decent middle ground between responsiveness and information shown.
> Show loading text in favourites list

- src/assets/styles/style.less
- src/main/main-directive.js
- src/toolbar/toolbar-controller.js
Closes (and uses the approach in) #516
> Remove animations on compact change

- src/sidebars/favourites/tearout-directive.js
> Refactor tearout directive

- src/sidebars/sidebar.less
> Z-index increased for recently closed windows to fix rendering.

- src/closedWindows/closedWindowList/closedWindowList-controller.js
- src/store-service.js
- src/window-service.js
Feels like this belongs more in the window service.
> Move closed window listener

- src/assets/styles/style.less
- src/main/main-controller.js
- src/main/main.html
- src/sidebars/favourites/tearout-directive.js
> Remove the bitflux tearout judder

- src/sidebars/favourites/favourites.less
- src/sidebars/favourites/geometry-service.js
- src/sidebars/favourites/tearout-directive.js
- src/sidebars/sidebar-directive.js
- src/sidebars/sidebar.html
- src/window-service.js
> Tearin indicator

- src/main/version/version.html
Closes #575 as per @rmarcalo sucestion
> Make github link more visible

- src/toolbar/toolbar-controller.js
> Correctly restores window sizes, fixing #579

- src/sidebars/favourites/tearout-directive.js
- src/window-service.js
> Tearout jank removed, closes #560

- src/closedWindows/closedWindowList/closedWindowList-controller.js
- src/toolbar/toolbar-controller.js
> Check windowService exists before adding listener

- src/window-service.js
> Fix restored windows removing other windows

- src/assets/styles/custom-scroll.less
> Scrollbar changed to reflect new design, closes #615

- src/sidebars/search/search-controller.js
Minor change so search selects first or current result. Fixes #160
> Enter in search selects first or current result for #160

- src/assets/styles/mixins.less
- src/assets/styles/style.less
- src/closedWindows/closedWindowList/closedWindowList.html
- src/sidebars/sidebar-compact.less
- src/toolbar/toolbar-mixins.less
- src/toolbar/toolbar.html
- src/toolbar/toolbar.less
> Toolbar draging, closes #556

- src/sidebars/favourites/tearout-directive.js
> Preserve indicators on tearout windows

- src/sidebars/favourites/favourite.html
- src/sidebars/favourites/minichart/minichart-controller.js
- src/sidebars/favourites/minichart/minichart-directive.js
- src/sidebars/favourites/minichart/minichart.html
- src/sidebars/favourites/minichart/minichart.less
See #643 
Example: stock code SKX.
> Minichart is self-contained; show error if not enough data

- src/sidebars/favourites/favourite-controller.js
> Only select a search item for bitflux when favouriting if there's no favourites

- package.json
- src/version-value.js
> Release 10.0.0-rc.1

- src/sidebars/favourites/favourite-controller.js
Closes #658. Also removes some unused variables
> Re-add percentage in favourites

- README.md
- gruntfile.js
- src/services/quandl-service.js
> Use separate API key in dev; edit readme

- src/app.json
> Use domstorage-flushing tag to make the app more reliably update state

- src/assets/styles/custom-scroll.less
- src/assets/styles/mixins.less
- src/assets/styles/style.less
- src/assets/styles/variables.less
- src/closedWindows/closedCard/closedCard.less
- src/main/main-compact.less
- src/main/version/version.less
- src/showcase/showcase-changes.less
- src/sidebars/favourites/favourites.less
- src/sidebars/favourites/minichart/minichart.less
- src/sidebars/search/search-compact.less
- src/sidebars/search/search.less
- src/sidebars/sidebar-compact.less
- src/sidebars/sidebar.less
- src/sidebars/star/star-compact.less
- src/sidebars/star/star.less
- src/toolbar/toolbar-compact.less
- src/toolbar/toolbar-mixins.less
- src/toolbar/toolbar.less
> Tidy LESS; Add position mixin

- .travis.yml
- README.md
- deploy.sh
- gruntfile.js
- package.json
- src/app.json
Closes #676
Looking for early feedback
> Auto deploy to develop and version on gh-pages.

- package.json
This reverts commit 89a53a51ed342f087762b2e631b84916c77f6afc, reversing
changes made to 004131ed9c41dbd973345539dedfae8169b8c7e5.
Interim for #696
> Revert "Resolve conflicts"

- src/sidebars/star/star.html
> Stop propagation on modal backdrop click

- src/assets/styles/variables.less
Tweaks the colours for the application, as per #705
> Colour adjustments

- README.md
- package.json
- src/app.json
- src/version-value.js
Patch release to fix the download link for #709 and update the links in app.json to master
> Hotfix 10.0.1

- src/assets/styles/style.less
- src/sidebars/sidebar-compact.less
closes [#700](https://github.com/ScottLogic/StockFlux/issues/700)
> adds border to windows

- src/.eslintrc
- src/closedWindows/closedCard/closedCard-controller.js
- src/index.html
- src/sidebars/favourites/favourite-controller.js
- src/sidebars/favourites/tearout-directive.js
- src/sidebars/search/search-controller.js
- src/sidebars/sidebar-controller.js
- src/sidebars/star/star-controller.js
- src/toolbar/toolbar-controller.js
> Added tracking code for google analytics

- src/sidebars/favourites/tearout-directive.js
This is quite a big issue and a trivial fix.
> Fix reporting issue with tearout start.

- src/store-service.js
> Don't persist empty closed windows

- .travis.yml
Add .npmrc and change path for downloading PhantomJS to fix Travis builds
See [link](https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs)
Attempt to fix #732
> Change PhantomJS download path

- src/sidebars/search/search.html
- src/sidebars/sidebar-controller.js
Closes [#707](https://github.com/ScottLogic/StockFlux/issues/707)
> clicking search icon now closes the search tab

- README.md
> Updated release section of README

- .travis.yml
Reverts ScottLogic/StockFlux#744
> Revert "Change PhantomJS download path"

- gruntfile.js
- package.json
- src/install.html
Fixes #712 - added a download page and removed the download grunt task + dependency
> Page with download link

- package.json
> Update bitflux to remove phantomjs build dep

- src/config-service.js
> Remove maxWidth and height as breaks maximise on latest runtime

- src/sidebars/favourites/tearout-directive.js
Timeouts kept firing after clicks - closes #765
>  Fixes tearout issue #765

- src/sidebars/sidebar-compact.less
Revert the height due to mixin
Fixes #737
> Fix compact scroll height

- src/sidebars/favourites/favourite-controller.js
- src/window-service.js
Fixes #769 by sorting out the race condition.
A test version can be downloaded [here](http://mbssantos.github.io/StockFlux/dev_restart2/install.html)
> Fixes race condition

- docs/TEST_PLAN.md
- package.json
- src/config-service.js
- src/sidebars/favourites/favourite-controller.js
- src/sidebars/favourites/tearout-directive.js
- src/sidebars/sidebar-compact.less
- src/version-value.js
- src/window-service.js
Merge release 10.1.0 branch back to dev
> Release 10.1.0

- ANALYTICS.md
- docs/ANALYTICS.md
Google analytics documentation request for #777
> docs: Create ANALYTICS.md

- package.json
- src/child/assets/styles/style.less
- src/child/components/SearchResult.js
- src/child/containers/App.js
- src/child/containers/showcase/Showcase.js
- src/child/containers/showcase/showcase-changes.less
- src/child/containers/sidebars/custom-scroll.less
- src/child/containers/sidebars/search/Search.js
- src/child/containers/sidebars/search/search.less
- src/child/containers/toolbar/Toolbar.js
- src/child/containers/toolbar/toolbar.less
- webpack.config.js
Could do with trying to find a nicer way to do the script imports
> Initial charts and updates to styles to prevent conflicts

- src/child/actions/sidebar.js
- src/child/assets/styles/style.less
- src/child/components/Favourite.js
- src/child/components/SearchResult.js
- src/child/components/minichart/Minichart.js
- src/child/components/minichart/minichart.less
- src/child/containers/sidebars/favourites/Favourites.js
- src/child/containers/sidebars/search/Search.js
- src/child/containers/sidebars/search/search.less
- src/child/reducers/reducers.js
- src/child/services/QuandlService.js
Added minichart, simplified favourite state & refactored isFavourite logic
> Added minichart to Favourite

- src/child/actions/sidebar.js
- src/child/components/Favourite.js
- src/child/containers/sidebars/favourites/Favourites.js
- src/child/containers/sidebars/favourites/favourites.less
- src/child/containers/sidebars/search/Search.js
- src/child/reducers/reducers.js
- Selection cleared if selcted stock is unfavourited from Favourites
- Css change to position star icon
- Added arrow up/down to %
- Removed drag from Search
> Added Star icon to favourite and percentage arrow

- src/child/actions/sidebar.js
- src/child/components/Favourite.js
- src/child/containers/sidebars/search/Search.js
- src/child/reducers/reducers.js
- Removed sign from Favourite percentage
- Added timeout to search
- Display last sent request result, instead of last received
- Minor bug fixing
> Improved search

- src/child/actions/window.js
- src/child/containers/toolbar/Toolbar.js
- src/child/containers/toolbar/toolbar.less
- src/child/reducers/reducers.js
- Fixed maximize
- Streamlined logic
- Minor style fixes
> Improved toolbar

- package.json
Fixes a bug with zooming in the navigator
> Update BitFlux to 1.6.1

- .eslintrc
- .travis.yml
- package.json
- src/child/components/SearchResult.js
- src/child/components/minichart/Minichart.js
- src/shared/ConfigService.js
- webpack.config.js
- fix `npm install` and Grunt issues with BitFlux
- run ESLint on Travis and fix the violations ([prefer-template](http://eslint.org/docs/rules/prefer-template), [no-param-reassign](http://eslint.org/docs/rules/no-param-reassign) and [no-unused-vars](http://eslint.org/docs/rules/no-unused-vars))
> Update Travis configuration and fix ESLint violations

- src/child/containers/sidebars/search/Search.js
- src/child/containers/sidebars/search/search.less
Adds a transition to the search input when the search tab is expanded/collapsed.
> Add transition to search text

- README.md
- openfin-launcher.js
- package.json
Just a few simple changes that hopefully make it easier to get the dev build running
> chore: simplified dev setup

- .travis.yml
- package.json
and remove global grunt-cli installation on Travis
> chore: add grunt-cli as a dev dependency for BitFlux build

- src/child/components/version/Version.js
- test/specs/child/components/version/VersionSpec.js
> test: add tests for Version component

- src/child/containers/sidebars/Sidebar.js
Removes console error.
Bug shows when toggling favourite in compact view.
> fix: Added bindings prop to search in compact view

- src/child/components/Favourite.js
- src/child/containers/sidebars/favourites/Favourites.js
> Double clicking a favourite in compact view opens full view

- src/child/actions/window.js
- src/child/services/currentWindowService.js
- test/helper/currentWindowServiceStub.js
- test/specs/child/actions/favouritesSpec.js
- test/specs/child/actions/searchSpec.js
- test/specs/child/actions/selectionSpec.js
- test/specs/child/actions/sidebarSpec.js
- test/specs/child/actions/windowSpec.js
- test/specs/child/selectors/selectorsSpec.js
Just a few basic tests and creation of a stub for the current window service.
> test: add more tests for window action creators

- src/child/components/favourite/Favourite.js
- src/child/containers/sidebars/favourites/Favourites.js
- src/child/index.js
- src/parent/actions/parent.js
- src/parent/reducers/dragOut.js
- src/parent/reducers/reducers.js
- src/parent/services/ParentService.js
- src/shared/constants/actionTypes.js
- test/specs/parent/reducers/reducersSpec.js
> feat: drag out favourite to spawn new window

- src/parent/services/ParentService.js
- src/shared/ConfigService.js
> fix: compact/maximized works with state persisting

- deploy.sh
- openfin-config/updateForDeployment.js
The `react_redux` directory will also need to be removed from the `gh-pages` branch.
> chore: update to no longer deploy react_redux branch

- package.json
- src/child/services/QuandlService.js
see: https://blog.quandl.com/change-quandl-api-limits
> fix: limit concurrent Quandl API requests

- package.json
- src/child/components/favourite/Favourite.js
- src/child/containers/showcase/Showcase.js
- src/child/services/QuandlService.js
- test/fixture/quandlMetadataResponse.json
- test/fixture/quandlSearchResponse.json
- test/fixture/quandlStockDataResponse.json
- test/helper/fakeQuandlServer.js
- test/specs/child/actions/searchSpec.js
- test/specs/child/services/QuandlServiceSpec.js
> fix: replace deprecated Quandl WIKI database with EOD database

- docs/TEST_PLAN.md
- package.json
- src/child/components/favourite/Favourite.js
- src/child/containers/showcase/Showcase.js
- src/child/services/QuandlService.js
- test/fixture/quandlMetadataResponse.json
- test/fixture/quandlSearchResponse.json
- test/fixture/quandlStockDataResponse.json
- test/helper/fakeQuandlServer.js
- test/specs/child/actions/searchSpec.js
- test/specs/child/services/QuandlServiceSpec.js
Release candidate http://scottlogic.github.io/StockFlux/11.2.0-rc/install.html
> Release 11.2.0

- src/child/components/minichart/minichart.less
- src/child/containers/sidebars/favourites/favourites.less
Closes #1013 
Stock price no longer left behind!
> fix: ensure stock price is dragged with tile

- openfin-config/app.dev.json
- package.json
- src/child/services/LayoutsService.js
- src/parent/services/LayoutsService.js
- test/helper/fakeOpenFin.js
- test/specs/child/services/LayoutsServiceSpec.js
- test/specs/parent/services/LayoutsServiceSpec.js
> refactor: upgrade openfin-layouts version

- INTERACTIONS.md
- stockflux-components/src/index.css
- stockflux-search/public/app.dev.json
- stockflux-search/public/index.html
- stockflux-search/src/App.js
- stockflux-search/src/components/Search.js
- stockflux-search/src/components/Search.module.css
- stockflux-search/src/components/SearchResult.js
- stockflux-search/src/components/SearchResult.module.css
- stockflux-search/src/components/custom-scroll.css
- stockflux-search/src/index.js
Felt like i should get this merged before a larger refactor of the search application begins. This will atleast allow people to try out the search application if they please, even if it isn't the finished deal.
> WIP Search 

- stockflux-components/src/index.css
- stockflux-search/src/App.module.css
- stockflux-search/src/search-result/SearchResult.module.css
> Searchbar dark theme

- stockflux-components/src/custom-hooks/LocalStorageHook.js
- stockflux-components/src/index.js
- stockflux-watchlist/src/components/Minichart/Minichart.js
- stockflux-watchlist/src/components/Watchlist/Watchlist.js
- stockflux-watchlist/src/components/WatchlistCard/UnwatchConfirmation.js
- stockflux-watchlist/src/components/WatchlistCard/WatchlistCard.Dragging.js
- stockflux-watchlist/src/components/WatchlistCard/WatchlistCard.js
1) IntentListener hack
2) useLocalStorage custom Hook
3) dragOver fix
> Intent Listener hack, dragOver fix and custom useLocalStorage hook

- stockflux-chart/public/app.dev.json
- stockflux-core/src/services/StockFluxService.js
- stockflux-search/public/app.dev.json
- stockflux-watchlist/public/app.dev.json
Also added the customData into the local app.json files
> Pull aws url from the customData from the app json file

- stockflux-core/src/services/StockFluxService.js
- stockflux-watchlist/src/components/Minichart/Minichart.js
- stockflux-watchlist/src/components/WatchlistCard/WatchlistCard.js
1) Error Handling for unknown symbol fetch:
2) "Fetching security data" message before displaying chart:
3) Updated AWS hyperlinks
> Watchlist card fetch data error handling

- .circleci/config.yml
- stockflux-components/src/index.js
- stockflux-launcher/package.json
- stockflux-launcher/public/index.html
Currently running on all branches, will add in filter to only run on dev when CRA-WIP is merged in
> Created Circle CI config file 

- stockflux-chart/package-lock.json
- stockflux-chart/package.json
- stockflux-chart/src/App.js
- stockflux-news/src/App.js
Solved the issue when the user manually refreshes the app the current symbol is lost
> Persist symbols and name for chart and news app

- stockflux-chart/package-lock.json
- stockflux-chart/package.json
- stockflux-chart/src/App.js
- stockflux-chart/src/components/Chart.js
- stockflux-chart/src/styles/app.css
- Added links to the news and watchlist apps.
- Added button to refresh the data
- Refactored structure of chart app by pulling bitflux instance of the chart to the top level
> Chart Navigation Icons

- stockflux-watchlist/src/components/watchlist-card/WatchlistCard.js
Also moved open chart click handler
> Fix issue that broke cards when API doesnt return 200

- stockflux-watchlist/README.md
This is an initial proposal for the updated README.md. Please, feel free to suggest what else can be added or amended.
> Update Watchlist's README.md

- stockflux-components/package-lock.json
- stockflux-core/package-lock.json
- stockflux-launcher/src/index.css
- stockflux-securities-master/package-lock.json
- stockflux-securities-master/package.json
- stockflux-securities-master/public/app.dev.json
- stockflux-securities-master/public/index.html
- stockflux-securities-master/src/App.js
- stockflux-securities-master/src/index.css
- stockflux-securities-master/src/index.js
Setting up the open fin set-up with create react app for the securities master.
> Securities Master Open fin setup

- stockflux-securities-master/public/app.dev.json
- stockflux-securities-master/src/App.js
- stockflux-securities-master/src/components/SecuritiesTable.css
- stockflux-securities-master/src/components/SecuritiesTable.js
- stockflux-securities-master/src/index.css
The table for the landing page of the securities app has been created. The table displays hard coded data for now.
> Created Securities Master Table Grid Layout with Stock Flux Themed Styling

- stockflux-bitflux/src/assets/js/data/stockflux/historic/feedAdaptor.js
- stockflux-chart/package-lock.json
- stockflux-chart/src/App.js
- stockflux-components/package-lock.json
- stockflux-components/package.json
- stockflux-components/src/components/Titlebar/Titlebar.js
- stockflux-components/webpack.config.js
- stockflux-container/package-lock.json
- stockflux-container/package.json
- stockflux-container/src/App.js
- stockflux-core/src/index.js
- stockflux-core/src/openfin-api-utils/openfinApiHelpers.js
- stockflux-core/src/services/StockFluxService.js
- stockflux-launcher/package-lock.json
- stockflux-launcher/src/App.js
- stockflux-launcher/src/app-shortcuts/AppShortcuts.js
- stockflux-launcher/src/free-text-search/FreeTextSearch.js
- stockflux-launcher/src/free-text-search/search-result/SearchResults.launcher.js
- stockflux-launcher/src/toolbar/CloseButton.js
- stockflux-news/package-lock.json
- stockflux-news/src/App.js
- stockflux-news/src/components/news-item/NewsItem.js
Move out all basic `window.fin` calls to `stockflux-core`
> Refactor openfin api calls

- stockflux-securities-master/package-lock.json
- stockflux-securities-master/package.json
- stockflux-securities-master/public/index.html
- stockflux-securities-master/src/App.js
- stockflux-securities-master/src/components/InputForm.css
- stockflux-securities-master/src/components/InputForm.js
- stockflux-securities-master/src/components/SecuritiesTable.css
- stockflux-securities-master/src/components/SecuritiesTable.js
- stockflux-securities-master/src/index.js
A router has been set up from the securities table to the newly created form component for editing or adding components.
> Add securities and edit form created along with routing from table

- stockflux-securities-master/src/components/InputForm.css
- stockflux-securities-master/src/components/InputForm.js
- stockflux-securities-master/src/components/SecuritiesTable.js
- stockflux-securities-master/src/services/SecuritiesService.js
Created a securitiesService file and moved the getSecuritiesData API call from the component to this file.
The event prevent default has also been added to the form submit to prevent the page from refreshing each time.
> Adding services for securities table

- README.md
> 1326: Ensure images are visible in markdown

- packages/stockflux-launcher/public/childWindow.css
Relates to [https://github.com/ScottLogic/StockFlux/issues/1320](url)
> 1320 - Updated spinner positioning

- packages/stockflux-watchlist/public/preview-chart.html
Update the chart preview window to match UX designs.
> Preview Window - Update to match UX designs

- packages/stockflux-components/src/components/Titlebar/Titlebar.js
- packages/stockflux-components/src/components/buttons/dialog-button/DialogButton.css
- packages/stockflux-components/src/components/buttons/dialog-button/DialogButton.js
- packages/stockflux-components/src/components/popups/ConfirmationWindow.js
- packages/stockflux-components/src/components/popups/PopupWindow.js
- packages/stockflux-components/src/index.css
- packages/stockflux-launcher/public/popupWindow.css
- packages/stockflux-launcher/src/App.css
Update confirmation dialog box to keep with new UX designs
- Remove border
- Change icons to words
- Larger buttons for selection options
- Centre dialog text accordingly. 
Unable to match specs on 
- Rounded border of the window. 
Need to confirm colours, as they do not appear to match the main colours being used within Stockflux.
> UX refactor dialog box

- package-lock.json
- packages/stockflux-launcher/package-lock.json
Run `npm audit fix` to fix security vulnerabilities.
> run npm audit fix

- packages/stockflux-chart/src/App.js
- packages/stockflux-launcher/src/free-text-search/FreeTextSearch.js
- packages/stockflux-watchlist/src/App.js
Prevent close of search box window when side mounted on the removal of text.
> stop close window on text delete if side docked

- packages/stockflux-watchlist/src/components/minichart/Minichart.js
- packages/stockflux-watchlist/src/components/watchlist-card/WatchlistCard.css
- packages/stockflux-watchlist/src/components/watchlist-card/WatchlistCard.js
Changed the wording when no results are returned
> 1412 change wording on Watch List

- package.json
- packages/stockflux-chart/package.json
- packages/stockflux-components/package.json
- packages/stockflux-container/package.json
- packages/stockflux-core/package.json
- packages/stockflux-launcher/package.json
- packages/stockflux-news/package.json
- packages/stockflux-watchlist/package.json
> update core to 13.1.0
