ScottLogic/StockFlux

- public/.eslintrc
- public/index.html
- public/quandl-service.js
- public/search-controller.js
- public/stock-controller.js
- public/stockData.html
Fetches financial data. Note the UI has not been designed, so I've included a skeleton just to show that data is being received, asynchronously.
As discussed first all the search results for the query are populated, and when they are all fetched the extra data for them all is then requested and displayed.
> Fetch Quandl financial data (closes #48)

- public/index.html
- public/store-service.js
- public/thumbnails-controller.js
This is the first part, creating a first time list of visited stocks (yet to be decided), and incrementing how many times each has been clicked, to re-order them on reload. Also internally there's now a limit of thumbnails (set to 9).
This makes use of angular-storage.
The next part will be to add new stocks to the list, after #49.
> Save list of searched stocks (part 1)

- public/index.html
- public/openfin-service.js
- public/stock-controller.js
- public/stockData.html
- public/thumbnails-controller.js
- public/thumbnails.html
- src/assets/styles/style.less
Allow showcase to be opened from search page. Store searched stocks locally and display as thumbnails.
> Open showcase from search, save searched stocks

- src/sidebars/favourites/favourites.js
The problem was the stocks were being cleared, leading angular to not notice changes in the array as the DOM was reset. Probably.
> Remove visual flicker when changing favourites

- gruntfile.js
- package.json
- src/.eslintrc
- src/index.html
- src/showcase/showcase-directive.js
- src/showcase/showcase.html
This is still a bit rough, but I thought it was worth sharing. Hopefully this is heading in the right direction!
It's using the [jleft/d3fc-showcase#openfin-integration/](https://github.com/jleft/d3fc-showcase/tree/openfin-integration)
The showcase can now be exported as a module, using `grunt:module` with a _very_ simple API
```js
// Create a instance of the showcase app
var chart = showcase.app();
// Renders the app into the specified element
chart.run(element);
// Given a string of a Quandl product, this will change the product which the chart is displaying
chart.changeQuandlProduct(productString);
// Thinking of removing this - it allows the callback to manipulate the model
// very flexible, but (hopefully) YAGNI
chart.updateModel(callback);
```
> Integrate d3fc-showcase as a module; remove iframe

- src/assets/styles/style.less
Disables selection across the whole app. I don't think it makes sense anywhere to have anything selected?
> Disable selection (closes #177)

- src/app.json
The minimum size leaves a 20px padding on the left of the logo, as it is on the right. The ratios for the minimum and default are 16:9.
> Default and minimum sizing

- src/sidebars/star.html
The bug was also present on the search cards. Thanks to good design ( ;-) ) it's now fixed in both!
> Don't select favourite/search card when toggling icon

- src/sidebars/search/search-controller.js
The way I see this possibly failing now is if retrieving a set of results is quicker than retrieving no results from a previous search.
While possible I don't think it's likely. Perhaps we should investigate a slight delay in searching after typing to make this even less likely?
> Fix no results message

- src/sidebars/search/search.less
Looks a bit overkill but I removed bits at a time and it wouldn't work properly.
> Restore top splitter on search tab

- gruntfile.js
- package.json
- src/index.html
- src/showcase/showcase-directive.js
This updates integration of d3fc-showcase as a module, now that it has landed in the main repo: https://github.com/ScottLogic/d3fc-showcase/pull/537
Changes in d3fc-showcase:
- Bug fixes (see [the commit history](https://github.com/ScottLogic/d3fc-showcase/commits/2a659f6ae092c8cff85cfd956d271eb4f4e894c1) for more info)
- No longer fetch Coinbase products by default
- Navigator extent gradient! :rainbow: (May need to override some of our Less variables to get the correct colours)
- Fixes the indicator close label positioning (thanks for raising the issue :smiley:)
- Added a method to the showcase API to set the Quandl API key (#193)
Proposed changes to OpenFinD3FC (in this PR):
- Rather than using my branch, the dependency is linked to commit in the showcase's `develop` branch. When the …
> Update showcase integration

- src/showcase/showcase-changes.less
Uses a faded version of the brush's linear gradient. Only issue is that the opacity is 20% rather than 50, as 50% was too bright (this is an issue with the showcase, which I've raised)
> Update navigator to have a darker bg area and lighter brush

- src/showcase/showcase-changes.less
Uses a faded version of the brush's linear gradient. Only issue is that the opacity is 20% rather than 50, as 50% was too bright (this is an issue with the showcase, which I've raised)
> Update navigator to have a darker bg area and lighter brush (2!)

- src/sidebars/favourites/favourite-controller.js
- src/sidebars/favourites/favourite-directive.js
- src/sidebars/favourites/favourite.html
- src/sidebars/favourites/favourites.less
- src/sidebars/favourites/tearout.js
- src/sidebars/sidebar.html
Chose to remove tearing out from the tearout file itself, on mouse down. That way the tearout window won't be destroyed/recreated, which would introduce additional overhead to changing the number of favourites from 1 to 2 or vice versa.
> Disallow tearout of single favourite

- src/showcase/showcase-changes.less
Makes the drop down more like the UX Spec, the bottom border of the button is removed and overlaid on the menu to give the appearance of the 'tab'.
> Bring the selector dropdown more in line with spec

- src/parent-controller.js
- src/parentApp.js
- src/sidebars/favourites/tearout.js
- src/store-service.js
- src/window-service.js
The first commit updates the windowService to a more ES6 compliant style. The second one updates the `closed` variable for each window in the local storage, except for the final window which stays with `closed: false`.
I'm interested particularly in feedback for the `createWindow` and `createTearoutWindow` methods, as I'm not currently too happy with the responsibility and boundaries between the two.
> Cache closed window

- src/index.html
Award for the weirdest PR of the year. Adds in a `<U+FEFF>` byte order mark that somehow stops the chart shrinking issue.
> Fix chart shrinking issue

- src/.eslintrc
- src/sidebars/favourites/tearout.js
- src/window-service.js
Implements a cache of ready OpenFin windows to increase usability and performance for tearing out favourite cards into new windows. Only main application windows are pooled -- windows for tearout cards are still handled as they were before.
> Window pool

- src/app.js
- src/main/main-controller.js
- src/parent-controller.js
- src/sidebars/favourites/tearout.js
- src/sidebars/sidebar.html
- src/store-service.js
- src/toolbar/toolbar-controller.js
- src/window-service.js
Restore all windows to their previous state, now including compact view. Note when the app is requesting the services off the `window` object they may not be there yet. Angular will notice when the services are present and update accordingly. (E.g., on the `mainCtrl` when checking whether the window should be compact the service may not be present. However, when it does arrive this will be noticed. On my machine I don't see any weird visual behaviour when starting the app so I hope it's fast enough).
Also fixes a small bug where restoring from maximised via a drag didn't change the icon from restore back to maximise (a `function()` instead of `() =>` oversight).
> Persist compact view across runs

- src/sidebars/favourites/geometry-service.js
- src/sidebars/favourites/tearout.js
- src/window-service.js
Dragging a card outside of the favourites tab and releasing will now create a new window. Note that tearing in still applies to the whole window. Perhaps it should be changed for symmetry too? #435
> Tearout from favourites tab

- gruntfile.js
Reasoning for this change:
- `grunt dev` used to run the server off of Github Pages.
- The `target` variable set where to load the Openfin config, however the `createZip` task defines that by downloading from Openfin with the path as a GET parameter.
I might've missed something that's important, but I'm not too sure
Also aids #424
> Remove the need to specify target on grunt dev

- src/showcase/showcase-directive.js
Performs an additional check on start up for a selection, which happens on contact view expand. This is done because if you expand from contact view, it uses the data generator instead of stocks.
> Fix Bitflux selection not occurring on compact select+expand

- LICENSE
- README.md
closes #429 
The GPL documentation [encourages the addition of the notice to every source file](http://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile), but does not necessitate this. I'm not keen on adding repetitive boiler-plate to our code base, so we'll go with this more minimal version!
> Added GPL Licence

- gruntfile.js
This stops errors about `/dev/tty` on git bash.
> Change deploy upstream repo to use git@github path

- src/toolbar/toolbar-controller.js
#508 
this.maximisedEvent etc were bound after the ready event was bound, meaning that the listener callbacks weren't defined if OpenFin was already ready.
> Fix non-responsive state (Take 2)

- gruntfile.js
- src/main/version/version-controller.js
- src/main/version/version.html
- src/parent-controller.js
- src/parentApp.js
- src/store-service.js
- src/version-value.js
part of #592 
On start up, the application checks the `version` item in LocalStorage. It then parses the current version and the version in the storage, and compares major versions. If they're different, then the `update` function is run.
In this instance, it just removes the cache of windows/indicators, because I thought some functionality would be better than none. (Plus, since everything's downloaded at run time, we can change this in the next release and that newer code would be run.)
This PR also brings the version value used by angular into its own `version-value.js` file, and some very minor `grunt bump` changes.
> Save version in Local Storage

- src/window-service.js
Move openWindow command to before closed window recreated to make cache consistent; closing #650.
I removed the statement on line `268` as it was doing the same thing, just later on. (If the name exists, then it's marked as opened beforehand -- which I would class as better caching consistency; if the name doesn't, it's already marked as open in the default config)
> Fix crash when trying to open the same closed window twice

- src/sidebars/favourites/tearout-directive.js
A few notes:
* This is triggered on any blur event on the tearout window -- as a result of alt-tab, start keyboard button, right click. Maybe the `Escape` key should also trigger it?
* The event for `blur` is added/removed after the window is shown; it stops situations where you tearout, return and try to tearout and it instantly returns (probably due to hiding/showing the window).
* In this case, tearing out 'cancels' the tearout, so it doesn't tear between windows or create a new window.
> Fix blurred tearouts breaking the window; closes #538

- src/services/quandl-service.js
- src/sidebars/search/search-controller.js
A fairly hefty refactor of the search component:
Major changes:
* The search part of the Quandl service now callbacks with the array of all stocks, as opposed to calling back for each stock
* Refactored the store service checking to a function `hasStore`, which returns `true` if the store exists. If it doesn't, it checks to see if the store service is available to be bound, and binds it. Otherwise, it returns `false`. Removes a bit of code duplication.
* The favourite updates are now comprehensively applied using more up-to-date data from the store service
* Closes #639 
* Closes #641 
* Closes #663
> Search updates

- deploy.sh
- gruntfile.js
- package.json
* Uses the travis branch to determine the folder to push to #696 
* Builds two versions; the `TYPE` version, ie dev/master; and the `VERSION` version (ie 10.0.0)
* Will create a new `dev` folder instead of develop (bear in mind for #693)
> GH Pages Build Updates

- README.md
- package.json
- src/app.json
- src/version-value.js
Merge the 10.0.1 patch into dev.
Bump dev version to pre minor to prevent it overwriting master 10.0.1 gh-pages version. See #713
> Hotfix 10.0.1 devmerge

- src/config-service.js
- src/toolbar/toolbar-controller.js
- src/window-service.js
Closes #647 
* Adds a 'shared' config, which adds the shared values to main window/tearout card configs (less to maintain)
* Removes the compact window config in favour of checking to see if the window is indeed compact when it's about to be displayed, and then updating the compact flags. The positioning works between app runs because of `top-left`.
* Commit 3 closes #633 by adding a flag for `wasMaximised`, as the `restored` event fired when switching between maximised and compact view
> Resizability on compact-created windows

- src/sidebars/favourites/geometry-service.js
- src/sidebars/favourites/tearout-directive.js
Closes #636 -- intersection's done by intersection area with the card, as opposed to using the divider for intersection checks.
> Tearout card reordering is done by intersection area

- src/sidebars/favourites/favourite-compact.less
Closes #703 
Not sure why it was disabled before for compact?
> Restore transition for compact favourites scrollbar

- src/sidebars/star/star.html
Closes #731 
Adds a `mousedown` event to the confirmation modal to stop the propagation. I'd tried doing some pointer event CSS magic to hopefully make this a bit nicer to approach, but it didn't work, so this was the next best alternative
> Fix mousedown on favourite removal confirm button triggering hide modal

- src/config-service.js
- src/sidebars/favourites/favourite-controller.js
- src/sidebars/favourites/favourites.less
- src/sidebars/favourites/tearout-directive.js
This PR introduces tearing out the final stock in a window. As per #726 the window will fade after an amount of time after the card has been torn and left the tearout area, and will fade back in if the card stops moving.
Issues/bugs:
> Tearout single stocks WIP

- src/sidebars/favourites/tearout-directive.js
Overcomes issue with random resizing on some screen resolutions and pixel scales
[redo of PR #753](https://github.com/ScottLogic/StockFlux/pull/753)
> modifies tearout to use setBounds rather than moveTo

- deploy.sh
- gruntfile.js
Updated deploy script to publish to gh pages the following:
| Branch | gh-pages version  |
|--- |---|
|master| master and _version_ |
| dev | dev |
| release-* |  _version_-rc |
_version_ is from package.json
Closes #713 #595
> Prevent gh-pages version overwrites from dev build. 

- .travis.yml
Feel free to decline this, if there's a reason not to update :) but this should lead to more reliable builds.
This related to https://github.com/ScottLogic/StockFlux/issues/732#issuecomment-217374493
> Update Travis to run on Node 4.4.x to reduce build errors

- src/child/assets/styles/style.less
Not sure if we want this, but I find it fairly annoying that the no favourites image can be dragged.
> fix: prevent drag on no favourites image

- src/child/components/Favourite.js
- src/child/containers/sidebars/favourites/Favourites.js
Fixes https://github.com/ScottLogic/StockFlux/pull/809#discussion_r64578393
This uses react's synthetic events, so now the event handlers are removed automatically when a favourite is unmounted. See [here](https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#under-the-hood-autobinding-and-event-delegation).
> refactor: ensure event handlers are removed when unmounting favourite

- webpack/webpack.config.dev.js
Turns off these messages when running webpack dev server:
> chore: quieten webpack dev build

- src/child/components/SearchResult.js
- src/child/components/favourite/Favourite.js
- src/child/containers/sidebars/Sidebar.js
- src/child/containers/sidebars/favourites/Favourites.js
- src/child/containers/sidebars/favourites/favourites.less
- src/child/containers/sidebars/sidebar.less
Does not include the removal of a favourite from window X when dragged from window Y as this is covered by #864.
- Dragged tile will displace another tile when it is half intersecting it (vertically)
- Dragged tile can be dropped after the final tile (rather than in the space below the final tile)
- Cleaned up the transitions
- When dragging into another window, the tile can be dropped in the sidebar regardless of whether the favourites are displayed or not
> fix: fix drag and drop

- src/child/containers/sidebars/favourites/Favourites.js
Looks like the change to the actions missed this one.
Simple fix.
> fix: Double clicking a stock in compact view selects and opens full view

- package.json
- src/version-value.js
Reverts ScottLogic/StockFlux#799
10.2.0 was never released, primarily due to #603 not being resolved (#626 & #666 were also unresolved, although were unlikely to have blocked the release). Given that the React/Redux rewrite will likely be released soon, this version number is being reverted.
> Revert "Release 10.2.0"

- src/child/containers/toolbar/Toolbar.js
- src/parent/services/ParentService.js
Closing a window using `fin.desktop.Window.contentWindow.close()` does not trigger the `close-requested` event handler.
`fin.desktop.Window.close()` should be used to ensure the child window's root app component is unmounted.
> fix: close programmatically using OpenFin window

- openfin-config/app.dev.json
- openfin-config/app.prod.json
Rollback [OpenFin Runtime version](https://developer.openfin.co/versions/) from stable (6.49.16.16) to 5.44.12.27 to prevent maximize error, where window does not fill screen and does not resize properly.
> chore: rollback OpenFin Runtime version to prevent maximize error

- README.md
- src/static/install.html
Update OpenFin installer link from `https://dl.openfin.co/services/download` to `https://install.openfin.co/download`.
> docs: update OpenFin installer URL

- README.md
- src/child/services/QuandlService.js
- test/specs/child/services/QuandlServiceSpec.js
- webpack/webpack.config.dev.js
This PR makes `QUANDL_API_KEY` environment variable available in local (both development or production) environments.
At the moment the variable is only set automatically in Travis environment when running CI and building for deploy.
> fix: use QUANDL API key as environment variable in development mode

- .eslintrc
- .gitattributes
- .gitignore
- package-lock.json
ESLint is complaining about CRLF line endings. This is because we are extending airbnb rules, which include a rule to error on non-unix line endings.
We already have a `.gitattributes` file to normalize CRLF to LF when creating a commit, and we are all developing on Windows OS, so it makes sense to override the airbnb rule.
fixes #999
> Fix linter complaints about CRLF line endings

- src/child/containers/sidebars/search/search-compact.less
- src/child/containers/sidebars/search/search.less
Very basic and crude fix, increased right padding to 5 to shift the Close 'X' left, also decreased the padding of the input element so that the 'Enter stock name or symbol' is shifted slightly left as well.
> Issue #728 mis-alligned close button for search in compact mode fixed.

- package-lock.json
- package.json
Fixes an issue preventing redux devtools from loading successfully, simply by bumping to a more recent version.
> Bump remotedev-server version to fix redux devtools access

- src/child/containers/sidebars/search/search-compact.less
- src/child/containers/sidebars/search/search.less
Some css issues fixed here, for the window close button.
In particular, the non-specific use of `.close { display: none; }` was causing havoc!
> Fix close button issues due to nonspecific css

- src/parent/reducers/reducers.js
- src/parent/services/ParentService.js
Step 1 of fixing the bug described in #1006, in which a closed event is fired more than once for re-opened windows. A future PR will fix this properly.
> Temporary workaround for issue #1006

- src/child/components/SearchResult.js
- src/child/components/favourite/Favourite.js
- src/child/components/favourite/UnfavouriteConfirmation.js
- src/child/components/minichart/Minichart.js
- src/child/containers/App.js
- src/child/containers/sidebars/Sidebar.js
- src/child/containers/sidebars/closedWindows/ClosedWindows.js
- src/child/containers/sidebars/favourites/Favourites.js
- src/child/containers/sidebars/search/Search.js
- src/child/containers/toolbar/Toolbar.js
- src/child/propTypeShapes/favourites.js
- src/child/propTypeShapes/selection.js
- src/child/propTypeShapes/sidebar.js
- src/child/propTypeShapes/windowState.js
Updating the code to use the standalone prop-types package (which was added to package.json in a previous PR).
Plus some minor code cleanup, related to accessing props.
> Replace deprecated prop-types imports

- src/parent/reducers/reducers.js
- src/parent/services/ParentService.js
Store mapping of child windows by name, so that we can remove the `closed` event listener when a child window is closed.
fixes #1006
> Remove event handler when child window closed

- stockflux-chart-container/src/App.js
This will prevent instances of the chart container sitting idle as the user is unable to close the container manually
> Close the chart container when the last chart window is closed

- stockflux-launcher/src/free-text-search/FreeTextSearch.js
Close search results window when one of chart, news or watchlist is selected. 
Search query is cleared and the input is unfocused.
> Close search results window when an intent is fired

- stockflux-securities-master/src/App.js
- stockflux-securities-master/src/components/AddSecurityButton.css
- stockflux-securities-master/src/components/AddSecurityButton.js
- stockflux-securities-master/src/components/ErrorDisplayer.css
- stockflux-securities-master/src/components/ErrorDisplayer.js
- stockflux-securities-master/src/components/ErrorMessage.css
- stockflux-securities-master/src/components/ErrorMessage.js
- stockflux-securities-master/src/components/InputForm.js
- stockflux-securities-master/src/components/SecuritiesTable.css
- stockflux-securities-master/src/components/SecuritiesTable.js
Edit buttons on the form have been created for each security row which routes to the input form with a title that says "Edit Security". The add security button has been refactored into it's own component and routes to the input form showing the title "Create a Security".  The title is chosen by the presence of a securityId prop. 
The add securities button is now present in the top right corner when there are securities in the table.
> Create edit button on grid to open edit form

- stockflux-securities-master/src/components/AddSecurityButton.css
- stockflux-securities-master/src/components/InputForm.css
- stockflux-securities-master/src/components/InputForm.js
- stockflux-securities-master/src/components/SecuritiesTable.css
- stockflux-securities-master/src/components/SecuritiesTable.js
- stockflux-securities-master/src/services/SecuritiesService.js
The service for getting a single security has been added and is used in the edit form to fill the form with the security data for the selected security. As discussed the exchange and symbol are read-only in the edit form.
> Make Get Security Service to Fill Edit Form

- stockflux-securities-master/src/components/SecuritiesTable.js
In my last PR I was prompted to make this change which I didn't realise broke the security table making it not display the data in the table body. The table body only renders if error is _falsy_.and `[]` is not considered _falsy_ by javascript but `null` is.
> Fixed bug: security table body not displaying

- packages/stockflux-news/src/App.css
- packages/stockflux-news/src/App.js
- packages/stockflux-news/src/index.css
For #1140 
* Add button links to StockFlux news on header
Appearance:
Double line:
> Feat: news app links

- packages/stockflux-launcher/public/childWindow.css
- packages/stockflux-launcher/src/free-text-search/FreeTextSearch.css
- packages/stockflux-launcher/src/search-results/ChildWindow.js
Change the styling of the scroll results sections to use the same components for handling scrolling sections. 
The scroll  bar section should fade in when there is results to scroll and you are over the window.
> #1294 Search Results Scroll Behaviour

- packages/stockflux-components/src/components/scroll-wrapper-y/ScrollWrapperY.css
- packages/stockflux-components/src/index.css
- packages/stockflux-components/src/styles/scrollbar.css
Merge scrollbar changes into general UX feedback. 
- Remove hover to show scrollbar functionality
- change colours to use from `index.css` variables. 
Currently does not have the up/down arrows, need more research into webkit-scrollbar to get them to show correctly.
> change styling on scrollbars

- packages/stockflux-launcher/src/App.js
- packages/stockflux-launcher/src/free-text-search/FreeTextSearch.js
- packages/stockflux-launcher/src/search-results/helpers/Positioner.js
From Issue #1297 When the launcher bar is undocked the search results box appears in the 0,0 position. 
Fixed to work out where it should be showing from the window, works in both formats of the launcher (Horizontal / Vertical) and will handle if the launcher is dragged onto non-primary monitors. Should work on all sizes of launchers.
> 1297 undocked launcher search box

- packages/stockflux-chart/src/index.js
- packages/stockflux-container/src/App.js
- packages/stockflux-core/src/index.js
- packages/stockflux-core/src/openfin-api-utils/openfinApiHelpers.js
- packages/stockflux-launcher/src/index.js
- packages/stockflux-watchlist/src/components/notifications/Notification.js
- packages/stockflux-watchlist/src/components/watchlist-card/WatchlistCard.js
- packages/stockflux-watchlist/src/index.js
- packages/stockflux-watchlist/src/services/currentWindowService.js
Fixes #1182 
* Refactors any uses of `window.fin` or `fin.` to use `OpenfinApiHelpers`
> Refactor: Move all use of OpenFin API into stockflux-core

- packages/stockflux-watchlist/src/components/watchlist-card/WatchlistCard.js
- packages/stockflux-watchlist/src/components/watchlist/Watchlist.js
Restore functionality to the watch list cards. From when intents were used clicking on the chart in the watch list would open the chart. When intents were removed this no longer worked.
This restores the functionality using new methods which includes the window positioning correctly.
> Chart click option

- packages/stockflux-watchlist/src/App.css
- packages/stockflux-watchlist/src/components/minichart/constants.js
Modify the mini-chart on the watch list to be smaller to allow for 6 digit stock prices.
Before - 
After -
> change watchlist minichart size

- packages/stockflux-launcher/src/search-results/helpers/Positioner.js
Refers to [https://github.com/ScottLogic/StockFlux/issues/1328](url)
> 1328 - Updated positioning for launcher when docked to top

- packages/stockflux-bitflux/src/assets/styles/variables.css
- packages/stockflux-chart/src/styles/app.css
- packages/stockflux-components/src/index.css
Change existing windows to use the same colours as the new UX design. Contains no layout or behaviour changes.
Windows modified
- Chart
- News
- Launcher
- Popup Window
> UX - Change existing windows to new colours

- packages/stockflux-components/src/components/Titlebar/Titlebar.js
- packages/stockflux-watchlist/public/child-window.html
- packages/stockflux-watchlist/public/childWindow.css
- packages/stockflux-watchlist/public/popupWindow.css
Add a new parameter to the title bar options which will allow for close confirmation to be applied. 
`<Components.Titlebarr confirmClose={bool}>` can be used to toggle a confirmation dialog on close of a window. If the parameter is omitted or false no dialog is shown and windows close automatically. 
In order for popups to work correctly, the `.html` and `.css` files for the popup need to be included in the project which this is being used.
> add confirmClose option to titlebar

- packages/stockflux-components/src/components/Titlebar/Titlebar.css
- packages/stockflux-components/src/components/Titlebar/Titlebar.js
- packages/stockflux-launcher/src/App.css
Issue mentioned by @SL-SWoods: when clicking the minimise or close on the titlebar, you have to click the icon itself to get the onClick to fire. The highlighted bounding box is not interactive. 
This problem was being caused by the use of `display: inline-block` on the styles. 
* Removed `inline-block` and repeated style tags on launcher
* Make sure click works with bounding box with the `ConfirmationWindow` by moving the style to a div within the window
> Fix minimise and close to work with the whole bounding box area

- packages/stockflux-components/src/index.css
- packages/stockflux-news/src/App.css
- packages/stockflux-news/src/App.js
- packages/stockflux-news/src/components/news-item/NewsItem.css
- packages/stockflux-news/src/index.css
Update news to fit in with new UX standards.
- Colours updated to new standards
- Title bar matches watch list title bar.
- Placeholder for news 'tabs'.
> News: Change layout to new ux standard

- developer-proxy/readMe.md
- developer-proxy/src/static/apps.json
- packages/stockflux-components/src/components/buttons/borderless-buttons/app-shortcuts/External.js
- packages/stockflux-components/src/components/buttons/round-button/RoundButton.css
- packages/stockflux-components/src/index.js
- packages/stockflux-launcher/src/App.css
- packages/stockflux-launcher/src/app-shortcuts/AppShortcuts.js
Modify the launcher to allow multiple apps to show on the launcher.
Includes ReadMe file within `developer-proxy` with instructions on how to add new options to the list.
> allow use of extra apps in the launcher
